NumPy is a package for numerical computing. It provides many functionalities for statistics and random number generation.

The modules available in the package may be used in a python script after they are imported.

Importing a module enables you to access its global variables and functions.

In [2]:
import numpy as np

The main object in NumPy is the multidimensional array. You can work with them in a similar way as you would with Matlab vectors and matrices.

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b = np.arange(9).reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
c = np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

In [42]:
c.reshape((4,1)) # does not change original array c

array([[0.],
       [0.],
       [0.],
       [0.]])

In [9]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [21]:
e = np.random.random((3,3)) # Unif[0,1)
e

array([[0.19187147, 0.39957031, 0.86858283],
       [0.71897584, 0.13828002, 0.99673459],
       [0.32737604, 0.97763367, 0.67402997]])

In [22]:
10*e

array([[1.91871468, 3.99570315, 8.68582832],
       [7.18975842, 1.38280015, 9.9673459 ],
       [3.27376041, 9.77633674, 6.74029967]])

In [15]:
vector = np.linspace(0,10,11) # (start, end, #points)
vector

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
a*b

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [30]:
a.dot(b)

array([24, 30, 36])

In [32]:
b<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [34]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [35]:
vector[0:4]

array([0., 1., 2., 3.])

In [36]:
vector[2:]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
vector[:5:-1]

array([10.,  9.,  8.,  7.,  6.])

In [44]:
f = np.floor(10*np.random.random((5,5)))
f

array([[2., 5., 9., 3., 1.],
       [5., 1., 2., 9., 0.],
       [9., 8., 2., 1., 0.],
       [3., 6., 1., 8., 5.],
       [5., 7., 2., 2., 1.]])

In [45]:
f[...,2]

array([9., 2., 2., 1., 2.])